[package]
name = "bt-gpu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bt-core = { workspace = true }
bt-atlas = { workspace = true }
objc2 = { workspace = true }
objc2-foundation = { workspace = true }
objc2-metal = { workspace = true }
objc2-quartz-core = { workspace = true, features = ["CALayer", "CAMetalLayer", "objc2-metal", "objc2-core-foundation"] }
dispatch2 = { workspace = true }
